//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public System.DateTime Date { get; set; }
        public string Reason { get; set; }
        public string Subject { get; set; }
    
        public virtual Subject Subject1 { get; set; }
        public virtual User User { get; set; }
    }
}
