//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupSubject
    {
        public int Id { get; set; }
        public Nullable<short> Group { get; set; }
        public string Subject { get; set; }
    
        public virtual Subject Subject1 { get; set; }
    }
}
