//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public short Group { get; set; }
        public short SubGroup { get; set; }
        public byte Week_Num { get; set; }
        public string Subject { get; set; }
        public byte Subject_Num { get; set; }
        public string Subject_Type { get; set; }
        public string Auditorium { get; set; }
        public byte Day { get; set; }
        public int Id { get; set; }
        public Nullable<byte> Kurs { get; set; }
    
        public virtual Subject Subject1 { get; set; }
    }
}
