//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public short Group { get; set; }
        public int Kurs { get; set; }
        public short SubGroup { get; set; }
        public string UserName { get; set; }
        public string Phone { get; set; }
    
        public virtual User User { get; set; }
    }
}
